//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Varanegar2017.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentPreviousJobs
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> fk_AgentId { get; set; }
        public string JobPlaceName { get; set; }
        public string IndustryType { get; set; }
        public Nullable<int> JobStartYear { get; set; }
        public Nullable<int> JobFinishDate { get; set; }
        public string JobDescription { get; set; }
        public string JobPost { get; set; }
    
        public virtual AgentQuestionaries AgentQuestionaries { get; set; }
    }
}
