//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Varanegar2017.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentQuestionaries
    {
        public AgentQuestionaries()
        {
            this.AgentPreviousJobs = new HashSet<AgentPreviousJobs>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<bool> IsCompany { get; set; }
        public string FullName { get; set; }
        public string BirthCerId { get; set; }
        public string NationalCode { get; set; }
        public string BirthPlace { get; set; }
        public string HomeAddress { get; set; }
        public string Phone { get; set; }
        public string PostalCode { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public Nullable<bool> IsSellSoftwar { get; set; }
        public string SellSoftwareDesc { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddress { get; set; }
        public string CompanyPhone { get; set; }
        public string CompanyOwnership { get; set; }
        public string CompanyArea { get; set; }
        public string CompanyPostalCode { get; set; }
        public string CompanyEmployeeNumber { get; set; }
        public Nullable<bool> IsHighSpeedInternet { get; set; }
        public Nullable<bool> IsInsurance { get; set; }
        public Nullable<bool> IsAgent { get; set; }
        public string IsAgentDesc { get; set; }
        public string VaranegarSoftwareIntroduce { get; set; }
        public Nullable<bool> IsCommercialPlace { get; set; }
        public string IsCommercialPlaceDesc { get; set; }
        public string ReasonForDo { get; set; }
        public string HowKnowUs { get; set; }
        public Nullable<int> fk_CityId { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public string Browser { get; set; }
        public string Ip { get; set; }
        public string Os { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
    
        public virtual ICollection<AgentPreviousJobs> AgentPreviousJobs { get; set; }
    }
}
