//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Varanegar2017.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CareerForm
    {
        public System.Guid careerID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FatherName { get; set; }
        public string NationalSHCode { get; set; }
        public string NationalCode { get; set; }
        public string birthDate { get; set; }
        public string BirthPlace { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public Nullable<int> marriage { get; set; }
        public string childrenNumb { get; set; }
        public Nullable<int> HomeStatus { get; set; }
        public Nullable<bool> IsInsurance { get; set; }
        public Nullable<int> MilitaryStatus { get; set; }
        public Nullable<int> ExpertOn { get; set; }
        public string History { get; set; }
        public Nullable<int> degree { get; set; }
        public string major { get; set; }
        public string Software { get; set; }
        public Nullable<int> familiarIndustry { get; set; }
        public Nullable<int> languagesRate { get; set; }
        public Nullable<int> howtoFind { get; set; }
        public string howtoFindDesc { get; set; }
        public Nullable<bool> OvertimeWork { get; set; }
        public Nullable<bool> NightWork { get; set; }
        public Nullable<bool> missionWork { get; set; }
        public Nullable<bool> WeekendWork { get; set; }
        public Nullable<bool> Surgery { get; set; }
        public Nullable<bool> Conviction { get; set; }
        public Nullable<bool> Smoking { get; set; }
        public Nullable<bool> Warranty { get; set; }
        public Nullable<int> WorkingType { get; set; }
        public string FinalDesc { get; set; }
        public string sallary { get; set; }
        public string StartDate { get; set; }
        public string resumeFile { get; set; }
        public Nullable<bool> IsVisited { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public string Browser { get; set; }
        public string Ip { get; set; }
        public string Os { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string OtherExpertTitle { get; set; }
        public string OtherFamiliar { get; set; }
    }
}
