//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Varanegar2017.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        public Customers()
        {
            this.Rel_Customer_Province = new HashSet<Rel_Customer_Province>();
            this.Rel_Solutions_Customers = new HashSet<Rel_Solutions_Customers>();
        }
    
        public System.Guid CustomersID { get; set; }
        public System.Guid fk_CustomerGroupID { get; set; }
        public string CustomerTitle { get; set; }
        public string En_CustomerTitle { get; set; }
        public string CustomerName { get; set; }
        public string SuccessHistory { get; set; }
        public string En_SuccessHistory { get; set; }
        public Nullable<bool> IsInHome { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public Nullable<System.DateTime> submitDate { get; set; }
        public string ImgLogo { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> StartMonth { get; set; }
        public Nullable<int> StartYear { get; set; }
        public Nullable<int> FinishMonth { get; set; }
        public Nullable<int> FinishYear { get; set; }
        public Nullable<int> BranchNumber { get; set; }
        public string ImgLogo_Thumb { get; set; }
    
        public virtual CustomerGroups CustomerGroups { get; set; }
        public virtual ICollection<Rel_Customer_Province> Rel_Customer_Province { get; set; }
        public virtual ICollection<Rel_Solutions_Customers> Rel_Solutions_Customers { get; set; }
    }
}
