//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Varanegar2017.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DemoRequests
    {
        public int RequestID { get; set; }
        public string Name { get; set; }
        public string CompanyName { get; set; }
        public string Field { get; set; }
        public string Post { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public int fk_FamiliarMethodID { get; set; }
        public string FinalDesc { get; set; }
        public Nullable<bool> IsVisited { get; set; }
        public System.DateTime RegisterDate { get; set; }
        public string Browser { get; set; }
        public string Ip { get; set; }
        public string Os { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<int> fk_RecieverID { get; set; }
    
        public virtual EmailRecieverRoles EmailRecieverRoles { get; set; }
        public virtual FamiliarMethods FamiliarMethods { get; set; }
    }
}
