//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Varanegar2017.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamiliarMethods
    {
        public FamiliarMethods()
        {
            this.DemoRequests = new HashSet<DemoRequests>();
        }
    
        public int FamiliarMethodID { get; set; }
        public string FamiliarMethodTitle { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
    
        public virtual ICollection<DemoRequests> DemoRequests { get; set; }
    }
}
