//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Varanegar2017.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GalleryImages
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> fk_GalleryId { get; set; }
        public string Title { get; set; }
        public string Summery { get; set; }
        public string VideoLink { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public Nullable<int> Priority { get; set; }
    
        public virtual GalleryGroups GalleryGroups { get; set; }
    }
}
