//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Varanegar2017.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_SearchQueries
    {
        public int SearchID { get; set; }
        public string SearchQuery { get; set; }
        public System.DateTime SearchDate { get; set; }
        public string SearchIp { get; set; }
        public string RefrallPage { get; set; }
        public string browser { get; set; }
        public string OS { get; set; }
    }
}
