//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Varanegar2017.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_Errors
    {
        public int ErrorID { get; set; }
        public System.DateTime ErrorDate { get; set; }
        public string ErrorIp { get; set; }
        public string RefrallPage { get; set; }
        public string browser { get; set; }
        public string OS { get; set; }
    }
}
