//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Varanegar2017.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Managers
    {
        public int ManagerID { get; set; }
        public int Priority { get; set; }
        public string ManagerTitle { get; set; }
        public string ManagerPost { get; set; }
        public string ManagerDesc { get; set; }
        public string En_ManagerTitle { get; set; }
        public string En_ManagerPost { get; set; }
        public string En_ManagerDesc { get; set; }
        public string ManagerImg { get; set; }
        public string LinkedinLink { get; set; }
        public string EmailLink { get; set; }
        public System.DateTime SubmitDate { get; set; }
        public int UserSubmited { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public Nullable<int> UserLastUpdated { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<System.DateTime> deleteDate { get; set; }
    }
}
