//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Varanegar2017.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsLetters
    {
        public int id { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public string SubmitIP { get; set; }
        public string Browser { get; set; }
        public string OS { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
    }
}
