//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Varanegar2017.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public System.Guid ProductID { get; set; }
        public string ProductTitle { get; set; }
        public string En_ProductTitle { get; set; }
        public string ProductSumery { get; set; }
        public string En_ProductSumery { get; set; }
        public string ProductDesc { get; set; }
        public string En_ProductDesc { get; set; }
        public string ProductName { get; set; }
        public string ProductImage { get; set; }
        public Nullable<System.Guid> fk_ProductGroupID { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<System.DateTime> submitDate { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public Nullable<int> Priority { get; set; }
        public string ProductImage_Thumb { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ProductGroups ProductGroups { get; set; }
    }
}
