//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Varanegar2017.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductGroups
    {
        public ProductGroups()
        {
            this.ProductGroups1 = new HashSet<ProductGroups>();
            this.Products = new HashSet<Products>();
        }
    
        public System.Guid ProductGroupID { get; set; }
        public string ProductGroupTitle { get; set; }
        public string ProductGroupName { get; set; }
        public string ProductGroupImage { get; set; }
        public string ProductGroupDesc { get; set; }
        public string En_ProductGroupDesc { get; set; }
        public string En_ProductGroupTitle { get; set; }
        public string ProductGroupSummery { get; set; }
        public string En_ProductGroupSummery { get; set; }
        public Nullable<System.Guid> fk_ProductGroupID { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public Nullable<bool> IsDraft { get; set; }
        public string ProductGroupDesc_Draft { get; set; }
        public string En_ProductGroupDesc_Draft { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<ProductGroups> ProductGroups1 { get; set; }
        public virtual ProductGroups ProductGroups2 { get; set; }
        public virtual ICollection<Products> Products { get; set; }
    }
}
