//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Varanegar2017.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rel_Customer_Province
    {
        public int ID { get; set; }
        public int fk_ProvinceID { get; set; }
        public System.Guid fk_CustomerID { get; set; }
    
        public virtual Customers Customers { get; set; }
    }
}
