//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Varanegar2017.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceSteps
    {
        public ServiceSteps()
        {
            this.ServiceStepItems = new HashSet<ServiceStepItems>();
        }
    
        public System.Guid ServiceStepID { get; set; }
        public string ServiceStepTitle { get; set; }
        public string En_ServiceStepTitle { get; set; }
        public Nullable<System.Guid> fk_ServiceID { get; set; }
        public string ServiceStepImage { get; set; }
        public string ServiceStepDesc { get; set; }
        public string En_ServiceStepDesc { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public string ServiceStepName { get; set; }
        public string SmallDesc { get; set; }
        public string En_SmallDesc { get; set; }
    
        public virtual Services Services { get; set; }
        public virtual ICollection<ServiceStepItems> ServiceStepItems { get; set; }
    }
}
