//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Varanegar2017.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Services
    {
        public Services()
        {
            this.ServiceSteps = new HashSet<ServiceSteps>();
        }
    
        public System.Guid ServiceID { get; set; }
        public string ServiceTitle { get; set; }
        public string En_ServiceTitle { get; set; }
        public string ServiceName { get; set; }
        public string ServiceDesc { get; set; }
        public string En_ServiceDesc { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public string HeaderImg { get; set; }
        public string SmallDesc { get; set; }
        public string En_SmallDesc { get; set; }
    
        public virtual ICollection<ServiceSteps> ServiceSteps { get; set; }
    }
}
