//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Varanegar2017.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sliders
    {
        public int SliderID { get; set; }
        public string SliderTitle { get; set; }
        public string SmallText { get; set; }
        public string BigText { get; set; }
        public string LinkText { get; set; }
        public string LinkAddress { get; set; }
        public string SliderImageUrl { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public bool IsActive { get; set; }
        public int Priority { get; set; }
    }
}
