//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Varanegar2017.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolutionGroups
    {
        public System.Guid SolutionGroupID { get; set; }
        public string SolutionGroupTitle { get; set; }
        public string En_SolutionGroupTitle { get; set; }
        public string SolutionGroupName { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<int> Priority { get; set; }
    }
}
