//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Varanegar2017.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solutions
    {
        public Solutions()
        {
            this.Rel_Solutions_Customers = new HashSet<Rel_Solutions_Customers>();
        }
    
        public System.Guid SolutionID { get; set; }
        public Nullable<System.Guid> fk_SolutionGroupID { get; set; }
        public string SolutionTitle { get; set; }
        public string En_SolutionTitle { get; set; }
        public string SolutionName { get; set; }
        public string ImgBannerFile { get; set; }
        public string BannerText { get; set; }
        public string En_BannerText { get; set; }
        public string ProblemDesc { get; set; }
        public string En_ProblemDesc { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<int> Priority { get; set; }
        public string ProductInSupply { get; set; }
    
        public virtual ICollection<Rel_Solutions_Customers> Rel_Solutions_Customers { get; set; }
    }
}
